name: ABC
on: 
 workflow_dispatch:
 workflow_call:
 workflow_run:
          workflows: ["Job1", "Job2", "Job3"]
jobs:
  Flow1:
    if: success()
    needs: ["Job2"]
    runs-on: ubuntu-latest
    steps:
      - name: Rerun
        run: echo "hi"
  Flow2:
    if: success()
    needs: ["Job3"]
    runs-on: ubuntu-latest
    steps:
      - name: Rerun
        run: echo "hi"
          
    
