name: ABC
on: 
 workflow_dispatch:
 workflow_call:
 workflow_run:
          workflows: ["Job1"]
 
jobs:
  Build1:
    runs-on: ubuntu-latest 
    steps:
      - name: JOb1
        run: |
         echo "Job1 completed"
        
  
          
    
