name: retry the build
on: 
  workflow_dispatch:
jobs:
  Retry:
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Scripts to be added
      run: |
        echo "scripts ran" 
    - name: Build after failed
      uses: ./
      with:
          max_attempts: 2
          run: |
            echo "hellow world"
