name: fail build'
on:
  workflow_dispatch:

jobs:
  runs-on: ubuntu-latest
  
  steps:
   
   job1:
    - name: Sample1
      run: |
       echo "1 completed"
   job2:
      needs: job1
    - name: Sample2
      run: |
       echo "2 completed"
   job3:
    if: always()
    needs: [job1, job2]
