name: PowerBI
on: 
  workflow_dispatch:
  workflow_call:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run powershell
        run:
          ./Getdetails.ps1
      
