name: PowerBI
on: 
  workflow_dispatch:
  workflow_call:
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Run powershell
        shell: pwsh
        run:
          
          ./Getdetails.ps1
          
      
